[package]
name = "camera-controller"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gphoto = "0.1.2"
# iced = "0.1"
# gtk = "0.8.1"
# druid = "0.6.0"
# fltk = "0.7.8"
